version: "3.8"
services:
  node:
    env_file:
      - .env
    build:
      context: ./node
    volumes:
      - ./app:/usr/src/app

  chrome:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub
    env_file:
      - .env

  edge:
    image: selenium/node-edge:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub
    env_file:
      - .env

  firefox:
    image: selenium/node-firefox:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub
    env_file:
      - .env

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

volumes:
  node_modules:
    external: true
